### ISSUE TITLE
[BUG] Crash on map

### ISSUE THREAD

**Issue by thomhughes** [j-mie6/parsley#161]
## Description
Catastrophic crash with well-defined behaviour.

## Reproduction Steps
`("hello" *> ("skip" #> 2) <* "bye").map(x => x + 2).parse("helloskipbye")`

## Expected behavior
`Success(4)`

## Additional context
Parsley: 4.2.4

have fun :D

**Comment by j-mie6** [comment]
`java.lang.AssertionError: assumption failed: The pure in question is normalised to the end: if result is pure, after is empty.`
