### ISSUE TITLE
[Doc]: the limit of 22 generics is not a JVM limitation

### ISSUE THREAD

**Issue by xsh005** [j-mie6/parsley#242]
## Description
[Here](https://j-mie6.github.io/parsley/5.0/cheatsheet.html) it's incorrectly mentioned that: `The lift functions work all the way up to 22 arguments (which is a JVM limit).` It was actually a [scala 2](https://docs.scala-lang.org/scala3/reference/dropped-features/limit22.html) limitation (inherited from early versions of kotlin it seems).

**Comment by xsh005** [comment]
Hmm, I heard that this limit is just convenient for the scalac compiler? You could write a java function with 23 or more generic parameters.

**Comment by j-mie6** [comment]
Hmm, I think you might be right... I wonder where I had heard it was a JVM limit from? Nevertheless, I'll update it to make clear this was a Scala 2 decision (indeed, I still cross-build for Scala 2, so I can't exceed this limit anyhow)
