### ISSUE TITLE
Consider BSD3 license

### ISSUE THREAD

**Issue by rossabaker** [J-mie6/Parsley#5]
**Is your feature request related to a problem? Please describe.**
The http4s project is looking for a new, dotty-compatible parser library. Parsley looks encouraging, but the GPL is incompatible with our Apache 2 license.

**Describe the solution you'd like**
Consider licensing under BSD3, to match the Haskell implementation, or anything else compatible with Apache 2. Parsley is an exciting project, but the GPL licensing inhibits its use.

**Describe alternatives you've considered**
We are currently on parboiled2, but are blocked by its extensive use of macros. Fastparse has similar pros and cons. We are concerned that Atto will not be sufficiently performant.

Considered a cleanroom implementation of the newer Haskell version, but that would be redundant with the great work here, and risks some of the same problems as Scala's Parsec. I'd rather start from here, and consider how we can help bring it to parity with the insights in your recent Haskell paper.

**Additional context**
This is wonderful work that deserves more attention! Bravo!

**Comment by J-mie6** [comment]
License has been changed to BSD3, as requested!

I think that a more ground up approach might be less painful than trying to start from here: essentially, the lack of staging means there is a lot of specialist instructions in here that are mostly redundant. And the implementation isn't type-safe like the Haskell version is (in the sense it uses a lot of casting).

**Comment by rossabaker** [comment]
Thank you so much!  I just learned of this and the Haskell version yesterday and am still digesting both papers.  I'm excited to get deeper into these projects.
